package com.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Fleet implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID")
	private java.lang.String id;

	@org.kie.api.definition.type.Label("TargetCapacity")
	private java.lang.Integer targetCapacity;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("AvailabilityZone")
	private java.lang.String availabilityZone;

	@org.kie.api.definition.type.Label(value = "CurrentTime")
	private java.lang.Integer currentTime;

	@org.kie.api.definition.type.Label(value = "Filter")
	private java.lang.Boolean filter;

	public Fleet() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Integer getTargetCapacity() {
		return this.targetCapacity;
	}

	public void setTargetCapacity(java.lang.Integer targetCapacity) {
		this.targetCapacity = targetCapacity;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAvailabilityZone() {
		return this.availabilityZone;
	}

	public void setAvailabilityZone(java.lang.String availabilityZone) {
		this.availabilityZone = availabilityZone;
	}

	public java.lang.Integer getCurrentTime() {
		return this.currentTime;
	}

	public void setCurrentTime(java.lang.Integer currentTime) {
		this.currentTime = currentTime;
	}

	public java.lang.Boolean getFilter() {
		return this.filter;
	}

	public void setFilter(java.lang.Boolean filter) {
		this.filter = filter;
	}

	public Fleet(java.lang.String id, java.lang.Integer targetCapacity,
			java.lang.String name, java.lang.String availabilityZone,
			java.lang.Integer currentTime, java.lang.Boolean filter) {
		this.id = id;
		this.targetCapacity = targetCapacity;
		this.name = name;
		this.availabilityZone = availabilityZone;
		this.currentTime = currentTime;
		this.filter = filter;
	}

}