package com.resources;

import com.model.Fleet;

//from row number: 1
//Created from row 2
rule "Row 1 AdHocFleetCalculation"
	date-effective "27-Aug-2018"
	date-expires "30-Sep-2018"
	dialect "mvel"
	when
		fleetObject : Fleet( id == "sfr-e297b726-fa8b-490e-acdd-2b6c2420549a" , filter == "false" )
	then
		modify( fleetObject ) {
				setTargetCapacity( 12 )
		}
		System.out.println("Fired Ad Hoc");
end

//from row number: 2
//Created from row 3
rule "Row 2 AdHocFleetCalculation"
	date-effective "27-Aug-2018"
	date-expires "30-Aug-2018"
	dialect "mvel"
	when
		fleetObject : Fleet( id == "sfr-1ff95794-9d1e-4c86-8a05-d4e1de6395cb" , filter == "false" )
	then
		modify( fleetObject ) {
				setTargetCapacity( 12 )
		}
		System.out.println("Fired Ad Hoc");
end

//from row number: 3
//Created from row 4
rule "Row 3 AdHocFleetCalculation"
	date-effective "27-Sep-2018"
	date-expires "30-Sep-2018"
	dialect "mvel"
	when
		fleetObject : Fleet( id == "sfr-5f3d1af5-fc2c-41b0-95e2-3b895e8adc72" , filter == "false" )
	then
		modify( fleetObject ) {
				setTargetCapacity( 3 )
		}
		System.out.println("Fired Ad Hoc");
end
